BEGIN TRANSACTION;

INSERT INTO "KJVBook" (id, chs, book, abbr, slug)
VALUES
  (1, 50, 'Genesis', 'Gen, Gn, Ge', 'genesis'),
  (2, 40, 'Exodus', 'Exo, Ex, Exod', 'exodus'),
  (3, 27, 'Leviticus', 'Lev, Lv', 'leviticus'),
  (4, 36, 'Numbers', 'Num, Nm, Nu', 'numbers'),
  (5, 34, 'Deuteronomy', 'Deu, Dt, Deut', 'deuteronomy'),
  (6, 24, 'Joshua', 'Jos, Josh', 'joshua'),
  (7, 21, 'Judges', 'Jdg, Judg', 'judges'),
  (8, 4, 'Ruth', 'Rth, Rt, Rut, Ru', 'ruth'),
  (9, 31, '1 Samuel', '1 Sam, 1 Sa, 1 S, 1 Sm, 1sa', '1_samuel'),
  (10, 24, '2 Samuel', '2 Sam, 2 Sa, 2 S, 2 Sm, 2sa', '2_samuel'),
  (11, 22, '1 Kings', '1 Ki, 1 Kgs, 1ki', '1_kings'),
  (12, 25, '2 Kings', '2 Ki, 2 Kgs, 2ki', '2_kings'),
  (13, 29, '1 Chronicles', '1 Chr, 1 Ch, 1 Chron, 1ch', '1_chronicles'),
  (14, 36, '2 Chronicles', '2 Chr, 2 Ch, 2 Chron, 2ch', '2_chronicles'),
  (15, 10, 'Ezra', 'Ezr, Esr, 1 Ezr', 'ezra'),
  (16, 13, 'Nehemiah', 'Neh, Ne, 2 Ezr', 'nehemiah'),
  (17, 10, 'Esther', 'Est, Esth, es', 'esther'),
  (18, 42, 'Job', 'Job, Jb', 'job'),
  (19, 150, 'Psalms', 'Psa, Ps, Psalm', 'psalms'),
  (20, 31, 'Proverbs', 'Pro, Pr, Prov, Prv', 'proverbs'),
  (21, 12, 'Ecclesiastes', 'Ecc, Ec, Eccl', 'ecclesiastes'),
  (22, 8, 'Song of Solomon', 'Sng, Song, Canticles, Cant, so', 'song_of_solomon'),
  (23, 66, 'Isaiah', 'Isa, Is', 'isaiah'),
  (24, 52, 'Jeremiah', 'Jer, Jr', 'jeremiah'),
  (25, 5, 'Lamentations', 'Lam, La, Lm', 'lamentations'),
  (26, 48, 'Ezekiel', 'Ezk, Ez, Ezek, Eze', 'ezekiel'),
  (27, 12, 'Daniel', 'Dan, Da, Dn', 'daniel'),
  (28, 14, 'Hosea', 'Hos, Ho', 'hosea'),
  (29, 3, 'Joel', 'Jol, Jl, joe', 'joel'),
  (30, 9, 'Amos', 'Amo, Am', 'amos'),
  (31, 1, 'Obadiah', 'Oba, Ob, Obad, Obd', 'obadiah'),
  (32, 4, 'Jonah', 'Jon, Jnh', 'jonah'),
  (33, 7, 'Micah', 'Mic, Mi, Mch', 'micah'),
  (34, 3, 'Nahum', 'Nah, Na, Nam', 'nahum'),
  (35, 3, 'Habakkuk', 'Hab, Ha', 'habakkuk'),
  (36, 3, 'Zephaniah', 'Zeph, Zep', 'zephaniah'),
  (37, 2, 'Haggai', 'Hag, Hagg', 'haggai'),
  (38, 14, 'Zechariah', 'Zech, Zec, Zch', 'zechariah'),
  (39, 4, 'Malachi', 'Mal, Ml', 'malachi'),
  (40, 28, 'Matthew', 'Mt, Mat, Matt', 'matthew'),
  (41, 16, 'Mark', 'Mk, Mr, Mrk', 'mark'),
  (42, 24, 'Luke', 'Lk, Luk, L, Lu', 'luke'),
  (43, 21, 'John', 'Jn, Jhn, J, Joh', 'john'),
  (44, 28, 'Acts', 'Act, Ac', 'acts'),
  (45, 16, 'Romans', 'Rom, Ro, R, Rm', 'romans'),
  (46, 16, '1 Corinthians', '1 Cor, 1 Co, 1 K, 1ki', '1_corinthians'),
  (47, 13, '2 Corinthians', '2 Cor, 2 Co, 2 K, 2ki', '2_corinthians'),
  (48, 6, 'Galatians', 'Gal, Ga, G', 'galatians'),
  (49, 6, 'Ephesians', 'Eph, Ep, E', 'ephesians'),
  (50, 4, 'Philippians', 'Phil, Php, Ph, Phili', 'philippians'),
  (51, 4, 'Colossians', 'Col', 'colossians'),
  (52, 5, '1 Thessalonians', '1 Th, 1 Thess, 1 Thes, 1th', '1thessalonians'),
  (53, 3, '2 Thessalonians', '2 Th, 2 Thess, 2 Thes, 2th', '2_thessalonians'),
  (54, 6, '1 Timothy', '1 Tim, 1 Ti, 1 T, 1 Tm, 1ti', '1_timothy'),
  (55, 4, '2 Timothy', '2 Tim, 2 Ti, 2 T, 2 Tm, 2ti', '2_timothy'),
  (56, 3, 'Titus', 'Tit, Tt', 'titus'),
  (57, 1, 'Philemon', 'Phm, Phlm, Philem, Phile', 'philemon'),
  (58, 13, 'Hebrews', 'Heb, Hebr, H, Hbr', 'hebrews'),
  (59, 5, 'James', 'Jas, Jam, Ja', 'james'),
  (60, 5, '1 Peter', '1 Pet, 1 Pt, 1 P, 1 Pe, 1pe', '1_peter'),
  (61, 3, '2 Peter', '2 Pet, 2 Pt, 2 P, 2 Pe, 2pe', '2_peter'),
  (62, 5, '1 John', '1 Jn, 1 Jo, 1 J, 1jo', '1_john'),
  (63, 1, '2 John', '2 Jn, 2 Jo, 2 J, 2jo', '2_john'),
  (64, 1, '3 John', '3 Jn, 3 Jo, 3 J, 3jo', '3_john'),
  (65, 1, 'Jude', 'Jud, Jd', 'jude'),
  (66, 22, 'Revelation', 'Rev, ', 'revelation');

COMMIT;